#!/usr/bin/env bash
# Purpose: 
# Date:
# Kevin Burg - kevin.burg@state.co.us

# Misc variable definitions {{{
# set -x # Enable debug

# }}}

# Function definitions {{{

# }}}

# Begin main tasks {{{

# }}}

exit 0
